class Armas:
    def __init__(self):
        self.corpo_a_corpo_simples = {"Adaga": {"Preço": "2 po", "Dano": "1d4", "Peso": "0.5 kg",
                                                "Propriedades": ["Acuidade", "Leve", "Arremesso (distância 6/18)"]},
                                      "Azagaia": {"Preço": "5 pp", "Dano": "1d6", "Peso": "1 kg",
                                                  "Propriedades": ["Perfurante", "Arremesso (distância 9/36)"]},
                                      "Bordão": {"Preço": "2 pp", "Dano": "1d6", "Peso": "2 kg",
                                                 "Propriedades": ["Concussão, ""Versátil (1d8)"]},
                                      "Clava Grande": {"Preço": "2 pp", "Dano": "1d8", "Peso": "5 kg",
                                                       "Propriedades": ["Concussão", "Pesada", "Duas mãos"]},
                                      "Foice curta": {"Preço": "1 po", "Dano": "1d4", "Peso": "1   kg",
                                                      "Propriedades": ["Cortante", "Leve"]},
                                      "Lança": {"Preço": "1 po", "Dano": "1d6", "Peso": "1.5 kg",
                                                "Propriedades": ["Perfurante", "Arremesso (6/18)", "Versátil (1d8)"]},
                                      "Maça": {"Preço": "5 po", "Dano": "1d6", "Peso": "2 kg",
                                               "Propriedades": ["Concussão"]},
                                      "Machadinha": {"Preço": "5 po", "Dano": "1d6", "Peso": " 1kg",
                                                     "Propriedades": ["Leve Arremesso"]},
                                      "Martelo Leve": {"Preço": "2 po", "Dano": "1d4", "Peso": "1 kg",
                                                       "Propriedades": ["Concussão", "Leve",
                                                                        "Arremesso (distância 6/18)"]},
                                      "Porrete": {"Preço": "1 pp", "Dano": "1d4", "Peso": "1 kg",
                                                  "Propriedades": ["Concussão", "Leve"]}}

        self.distancia_simples = {"Arco Curto": {"Preço": "25 po", "Dano": "1d6", "Peso": "1 kg",
                                                 "Propriedades": ["Perfurante", "Duas mãos",
                                                                  "Munição (distância 24/96)"]},
                                  "Besta Leve": {"Preço": "25 po", "Dano": "1d8", "Peso": "2.5 kg",
                                                 "Propriedades": ["Perfurante", "Recarga", "Duas mãos",
                                                                  "Munição (distância 24/96)"]}}
